[package]
name = "rust_ffb_test"
version = "0.1.0"
authors = ["Michal Kajda <michal.kajda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flatbuffers = "0.8.3"